FROM openjdk:11
EXPOSE 43255
WORKDIR /usr/src/app

# Copy maven executable to the image
COPY ./mvnw .
COPY ./.mvn .mvn

# Copy the pom.xml file
COPY ./pom.xml .

# Copy the project source
COPY ./src ./src

RUN chmod 755 /usr/src/app/mvnw

RUN ./mvnw dependency:go-offline -B

RUN ./mvnw package -DskipTests
RUN ls -al
ENTRYPOINT ["java","-jar","target/pWebProject-0.0.1-SNAPSHOT.jar"]
